model:
    arch: MedT
data:
    dataset: BrainWeb
    train_split: train
    val_split: val
    path: datasets/brainweb/

training:
    gpu_idx: 0
    train_iters: 400
    batch_size: 4
    val_interval: 30
    n_workers: 4
    print_interval: 10
    optimizer:
        name: 'adam'
        lr: 6.0e-4
        weight_decay: 0.0005
    loss:
        name: 'cross_entropy'
    lr_schedule:
    resume:
    model_dir: trained_models/

testing:
    trained_model:
    path:
    boxplot: False