model:
    arch: MTUNet
data:
    dataset: BrainWeb_new
    train_split: train
    val_split: val
    path: /data/home/ywen/lk/datasets/mrbrains/
#    path: datasets/mrbrains/

training:
    gpu_idx: 0
    train_iters: 20000
    batch_size: 1
    val_interval: 100
    n_workers: 4
    print_interval: 50
    optimizer:
        name: 'adam'
        lr: 6.0e-4
        weight_decay: 0.0005
    loss:
        name: 'cross_entropy'
    lr_schedule:
    resume:
    model_dir: /data/home/ywen/lk/kkl_seg2021/kkl_segmentatiom/trained_models/MTUNet/brainweb
#    model_dir: trained_models/MTUNet
testing:
    trained_model:
    path:
    boxplot: