model:
    arch: new
data:
    dataset: MRBrainS
    train_split: train
    val_split: val
    path: ./datasets/mrbrains/

training:
    gpu_idx: 0
    train_iters: 20000
    batch_size: 1
    val_interval: 100
    n_workers: 4
    print_interval: 50
    optimizer:
        name: 'adam'
        lr: 6.0e-4
        weight_decay: 0.0005
    loss:
        name: 'cross_entropy'
    lr_schedule:
    resume:
    model_dir: ./trained_models/new

testing:
    trained_model: trained_models/UCTransNet/UNetTRD_MRBrainS.pkl
    path: trained_models/UCTransNet/images
    boxplot: False