model:
    arch: UCTransNet
data:
    dataset: HVSMR
    train_split: train
    val_split: val
    path: datasets/hvsmr2016/

training:
    gpu_idx: 0
    train_iters: 30000
    batch_size: 1
    val_interval: 500
    n_workers: 4
    print_interval: 100
    optimizer:
        name: 'adam'
        lr: 6.0e-4
        weight_decay: 0.0005
    loss:
        name: 'cross_entropy'
    lr_schedule:
    resume:
    model_dir: trained_models/UCTransNet

testing:
    trained_model: trained_models/NesTUnet/NestUnet_BrainWeb.pkl
    path: trained_models/NesTUnet/images
    boxplot: False